[package]
name = "jai-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
[dependencies]
jai-modules.workspace = true
jai-source.workspace = true
jai-platform.workspace = true
jai-lexer.workspace = true
jai-syntax.workspace = true
jai-sema.workspace = true
jai-vm.workspace = true
jai-types.workspace = true
sha2.workspace = true
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jai-platform = { workspace = true, features = ["native"] }
[lints]
workspace = true
