// Generated by generate.py: C functions reading aggregates through `va_arg`.
#include <stdarg.h>

typedef struct { long long f0; long long f1; } i64x2;
int va_i64x2(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i64x2 s = va_arg(ap, i64x2);
        ok = ok && s.f0 == ((long long) (seed + 1)) && s.f1 == ((long long) (seed + 2));
    }
    va_end(ap);
    return ok;
}
int vaafter_i64x2(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i64x2 s = va_arg(ap, i64x2);
        ok = ok && s.f0 == ((long long) (seed + 1)) && s.f1 == ((long long) (seed + 2));
    }
    va_end(ap);
    return ok;
}

typedef struct { signed char f0; int f1; } i8i32;
int va_i8i32(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i8i32 s = va_arg(ap, i8i32);
        ok = ok && s.f0 == ((signed char) (seed + 1)) && s.f1 == ((int) (seed + 2));
    }
    va_end(ap);
    return ok;
}
int vaafter_i8i32(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i8i32 s = va_arg(ap, i8i32);
        ok = ok && s.f0 == ((signed char) (seed + 1)) && s.f1 == ((int) (seed + 2));
    }
    va_end(ap);
    return ok;
}

typedef struct { signed char f0; signed char f1; signed char f2; } i8x3;
int va_i8x3(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i8x3 s = va_arg(ap, i8x3);
        ok = ok && s.f0 == ((signed char) (seed + 1)) && s.f1 == ((signed char) (seed + 2)) && s.f2 == ((signed char) (seed + 3));
    }
    va_end(ap);
    return ok;
}
int vaafter_i8x3(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i8x3 s = va_arg(ap, i8x3);
        ok = ok && s.f0 == ((signed char) (seed + 1)) && s.f1 == ((signed char) (seed + 2)) && s.f2 == ((signed char) (seed + 3));
    }
    va_end(ap);
    return ok;
}

typedef struct { int f0; int f1; int f2; int f3; int f4; } i32x5;
int va_i32x5(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i32x5 s = va_arg(ap, i32x5);
        ok = ok && s.f0 == ((int) (seed + 1)) && s.f1 == ((int) (seed + 2)) && s.f2 == ((int) (seed + 3)) && s.f3 == ((int) (seed + 4)) && s.f4 == ((int) (seed + 5));
    }
    va_end(ap);
    return ok;
}
int vaafter_i32x5(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i32x5 s = va_arg(ap, i32x5);
        ok = ok && s.f0 == ((int) (seed + 1)) && s.f1 == ((int) (seed + 2)) && s.f2 == ((int) (seed + 3)) && s.f3 == ((int) (seed + 4)) && s.f4 == ((int) (seed + 5));
    }
    va_end(ap);
    return ok;
}

typedef struct { long long f0; long long f1; long long f2; } i64x3;
int va_i64x3(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i64x3 s = va_arg(ap, i64x3);
        ok = ok && s.f0 == ((long long) (seed + 1)) && s.f1 == ((long long) (seed + 2)) && s.f2 == ((long long) (seed + 3));
    }
    va_end(ap);
    return ok;
}
int vaafter_i64x3(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i64x3 s = va_arg(ap, i64x3);
        ok = ok && s.f0 == ((long long) (seed + 1)) && s.f1 == ((long long) (seed + 2)) && s.f2 == ((long long) (seed + 3));
    }
    va_end(ap);
    return ok;
}

typedef struct { float f0; float f1; } f32x2;
int va_f32x2(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f32x2 s = va_arg(ap, f32x2);
        ok = ok && s.f0 == ((float) (seed + 1.5)) && s.f1 == ((float) (seed + 2.5));
    }
    va_end(ap);
    return ok;
}
int vaafter_f32x2(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f32x2 s = va_arg(ap, f32x2);
        ok = ok && s.f0 == ((float) (seed + 1.5)) && s.f1 == ((float) (seed + 2.5));
    }
    va_end(ap);
    return ok;
}

typedef struct { float f0; float f1; float f2; } f32x3;
int va_f32x3(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f32x3 s = va_arg(ap, f32x3);
        ok = ok && s.f0 == ((float) (seed + 1.5)) && s.f1 == ((float) (seed + 2.5)) && s.f2 == ((float) (seed + 3.5));
    }
    va_end(ap);
    return ok;
}
int vaafter_f32x3(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f32x3 s = va_arg(ap, f32x3);
        ok = ok && s.f0 == ((float) (seed + 1.5)) && s.f1 == ((float) (seed + 2.5)) && s.f2 == ((float) (seed + 3.5));
    }
    va_end(ap);
    return ok;
}

typedef struct { float f0; float f1; float f2; float f3; } f32x4;
int va_f32x4(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f32x4 s = va_arg(ap, f32x4);
        ok = ok && s.f0 == ((float) (seed + 1.5)) && s.f1 == ((float) (seed + 2.5)) && s.f2 == ((float) (seed + 3.5)) && s.f3 == ((float) (seed + 4.5));
    }
    va_end(ap);
    return ok;
}
int vaafter_f32x4(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f32x4 s = va_arg(ap, f32x4);
        ok = ok && s.f0 == ((float) (seed + 1.5)) && s.f1 == ((float) (seed + 2.5)) && s.f2 == ((float) (seed + 3.5)) && s.f3 == ((float) (seed + 4.5));
    }
    va_end(ap);
    return ok;
}

typedef struct { double f0; double f1; } f64x2;
int va_f64x2(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f64x2 s = va_arg(ap, f64x2);
        ok = ok && s.f0 == ((double) (seed + 1.5)) && s.f1 == ((double) (seed + 2.5));
    }
    va_end(ap);
    return ok;
}
int vaafter_f64x2(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f64x2 s = va_arg(ap, f64x2);
        ok = ok && s.f0 == ((double) (seed + 1.5)) && s.f1 == ((double) (seed + 2.5));
    }
    va_end(ap);
    return ok;
}

typedef struct { double f0; double f1; double f2; double f3; } f64x4;
int va_f64x4(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f64x4 s = va_arg(ap, f64x4);
        ok = ok && s.f0 == ((double) (seed + 1.5)) && s.f1 == ((double) (seed + 2.5)) && s.f2 == ((double) (seed + 3.5)) && s.f3 == ((double) (seed + 4.5));
    }
    va_end(ap);
    return ok;
}
int vaafter_f64x4(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f64x4 s = va_arg(ap, f64x4);
        ok = ok && s.f0 == ((double) (seed + 1.5)) && s.f1 == ((double) (seed + 2.5)) && s.f2 == ((double) (seed + 3.5)) && s.f3 == ((double) (seed + 4.5));
    }
    va_end(ap);
    return ok;
}

typedef struct { long long f0; double f1; } i64f64;
int va_i64f64(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i64f64 s = va_arg(ap, i64f64);
        ok = ok && s.f0 == ((long long) (seed + 1)) && s.f1 == ((double) (seed + 2.5));
    }
    va_end(ap);
    return ok;
}
int vaafter_i64f64(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        i64f64 s = va_arg(ap, i64f64);
        ok = ok && s.f0 == ((long long) (seed + 1)) && s.f1 == ((double) (seed + 2.5));
    }
    va_end(ap);
    return ok;
}

typedef struct { double f0; long long f1; } f64i64;
int va_f64i64(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f64i64 s = va_arg(ap, f64i64);
        ok = ok && s.f0 == ((double) (seed + 1.5)) && s.f1 == ((long long) (seed + 2));
    }
    va_end(ap);
    return ok;
}
int vaafter_f64i64(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f64i64 s = va_arg(ap, f64i64);
        ok = ok && s.f0 == ((double) (seed + 1.5)) && s.f1 == ((long long) (seed + 2));
    }
    va_end(ap);
    return ok;
}

typedef struct { float f0; int f1; } f32i32;
int va_f32i32(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f32i32 s = va_arg(ap, f32i32);
        ok = ok && s.f0 == ((float) (seed + 1.5)) && s.f1 == ((int) (seed + 2));
    }
    va_end(ap);
    return ok;
}
int vaafter_f32i32(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        f32i32 s = va_arg(ap, f32i32);
        ok = ok && s.f0 == ((float) (seed + 1.5)) && s.f1 == ((int) (seed + 2));
    }
    va_end(ap);
    return ok;
}

typedef struct __attribute__((packed)) { signed char f0; int f1; } pk_i8i32;
int va_pk_i8i32(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        pk_i8i32 s = va_arg(ap, pk_i8i32);
        ok = ok && s.f0 == ((signed char) (seed + 1)) && s.f1 == ((int) (seed + 2));
    }
    va_end(ap);
    return ok;
}
int vaafter_pk_i8i32(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        pk_i8i32 s = va_arg(ap, pk_i8i32);
        ok = ok && s.f0 == ((signed char) (seed + 1)) && s.f1 == ((int) (seed + 2));
    }
    va_end(ap);
    return ok;
}

typedef struct __attribute__((packed)) { signed char f0; double f1; } pk_i8f64;
int va_pk_i8f64(int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        pk_i8f64 s = va_arg(ap, pk_i8f64);
        ok = ok && s.f0 == ((signed char) (seed + 1)) && s.f1 == ((double) (seed + 2.5));
    }
    va_end(ap);
    return ok;
}
int vaafter_pk_i8f64(long long a1, long long a2, long long a3, long long a4, long long a5, long long a6, long long a7, int n, ...) {
    va_list ap;
    va_start(ap, n);
    int ok = 1;
    for (int i = 0; i < n; i++) {
        int seed = 7 + i * 3;
        pk_i8f64 s = va_arg(ap, pk_i8f64);
        ok = ok && s.f0 == ((signed char) (seed + 1)) && s.f1 == ((double) (seed + 2.5));
    }
    va_end(ap);
    return ok;
}
