[package]
name = "jai-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
jai-types.workspace = true
inkwell.workspace = true
jai-ir.workspace = true
jai-llvm.workspace = true
jai-source.workspace = true

[dev-dependencies]
jai-modules.workspace = true
jai-vm.workspace = true
jai-sema.workspace = true
jai-syntax.workspace = true


[lints]
workspace = true
