[package]
name = "jai-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
native = ["dep:jai-native-source"]

[dependencies]
jai-source.workspace = true
jai-vm.workspace = true
jai-native-source = { workspace = true, optional = true }

[lints]
workspace = true
