//! LLVM rendering consumes a resolved, immutable typed program.
use jai_sema::{
    Block, BoolExpr, Call, EntryPoint, Equality, Flow, IntExpr, IntOp, Local, Program, Relation,
    Statement, ValueExpr,
};
use std::fmt::{self, Write};

#[derive(Clone, Copy)]
struct IntRegister(usize);
#[derive(Clone, Copy)]
struct BoolRegister(usize);
#[derive(Clone, Copy)]
enum IntOperand {
    Constant(i64),
    Register(IntRegister),
}
#[derive(Clone, Copy)]
enum BoolOperand {
    Constant(bool),
    Register(BoolRegister),
}
#[derive(Clone, Copy)]
enum Label {
    Entry,
    Block(usize),
}
impl fmt::Display for IntOperand {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Constant(n) => write!(f, "{n}"),
            Self::Register(IntRegister(n)) => write!(f, "%v{n}"),
        }
    }
}
impl fmt::Display for BoolOperand {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Constant(n) => write!(f, "{}", u8::from(*n)),
            Self::Register(BoolRegister(n)) => write!(f, "%v{n}"),
        }
    }
}
impl fmt::Display for Label {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Entry => f.write_str("entry"),
            Self::Block(n) => write!(f, "bb{n}"),
        }
    }
}
fn local_type(local: Local) -> &'static str {
    match local {
        Local::Int(_) => "i64",
        Local::Bool(_) => "i1",
    }
}
fn local_index(local: Local) -> usize {
    match local {
        Local::Int(id) => id.index(),
        Local::Bool(id) => id.index(),
    }
}
fn return_type(ty: jai_syntax::ReturnType) -> &'static str {
    match ty {
        jai_syntax::ReturnType::Void => "void",
        jai_syntax::ReturnType::Value(jai_syntax::ScalarType::Int) => "i64",
        jai_syntax::ReturnType::Value(jai_syntax::ScalarType::Bool) => "i1",
    }
}
/// Semantic errors are ruled out by `jai_sema::resolve` before this boundary.
pub fn emit(program: &Program) -> String {
    let mut b = Builder {
        text: String::from("; Generated by the Rust Jai compiler.\n"),
        next_register: 0,
        next_block: 0,
        current: Label::Entry,
    };
    for p in program.procedures() {
        write!(
            b.text,
            "define {} @jai.p{}(",
            return_type(p.return_type),
            p.id.index()
        )
        .unwrap();
        for (i, local) in p.parameters.iter().enumerate() {
            if i != 0 {
                b.text.push_str(", ");
            }
            write!(b.text, "{} %arg{i}", local_type(*local)).unwrap();
        }
        b.text.push_str(") {\nentry:\n");
        b.current = Label::Entry;
        for local in &p.locals {
            b.line(format_args!(
                "%local{} = alloca {}",
                local_index(*local),
                local_type(*local)
            ));
        }
        for (i, local) in p.parameters.iter().enumerate() {
            b.line(format_args!(
                "store {} %arg{i}, ptr %local{}",
                local_type(*local),
                local_index(*local)
            ));
        }
        b.block(&p.body);
        if p.body.flow == Flow::FallsThrough {
            b.line(format_args!("ret void"));
        }
        b.text.push_str("}\n\n");
    }
    b.text.push_str("define i32 @main() {\nentry:\n");
    match program.entry() {
        EntryPoint::Void(id) => {
            b.line(format_args!("call void @jai.p{}()", id.index()));
            b.line(format_args!("ret i32 0"));
        }
        EntryPoint::Int(id) => {
            b.line(format_args!("%result = call i64 @jai.p{}()", id.index()));
            b.line(format_args!("%status = trunc i64 %result to i32"));
            b.line(format_args!("ret i32 %status"));
        }
    }
    b.text.push_str("}\n");
    b.text
}
struct Builder {
    text: String,
    next_register: usize,
    next_block: usize,
    current: Label,
}
impl Builder {
    fn line(&mut self, args: fmt::Arguments<'_>) {
        writeln!(self.text, "  {args}").unwrap();
    }
    fn int_result(&mut self, args: fmt::Arguments<'_>) -> IntOperand {
        let n = self.next_register;
        self.next_register += 1;
        self.line(format_args!("%v{n} = {args}"));
        IntOperand::Register(IntRegister(n))
    }
    fn bool_result(&mut self, args: fmt::Arguments<'_>) -> BoolOperand {
        let n = self.next_register;
        self.next_register += 1;
        self.line(format_args!("%v{n} = {args}"));
        BoolOperand::Register(BoolRegister(n))
    }
    fn label(&mut self) -> Label {
        let n = self.next_block;
        self.next_block += 1;
        Label::Block(n)
    }
    fn begin(&mut self, label: Label) {
        writeln!(self.text, "{label}:").unwrap();
        self.current = label;
    }
    fn jump(&mut self, label: Label) {
        self.line(format_args!("br label %{label}"));
    }
    fn block(&mut self, block: &Block) {
        for s in &block.statements {
            match s {
                Statement::StoreInt(id, e) => {
                    let v = self.int(e);
                    self.line(format_args!("store i64 {v}, ptr %local{}", id.index()));
                }
                Statement::StoreBool(id, e) => {
                    let v = self.boolean(e);
                    self.line(format_args!("store i1 {v}, ptr %local{}", id.index()));
                }
                Statement::ReturnVoid => self.line(format_args!("ret void")),
                Statement::ReturnInt(e) => {
                    let v = self.int(e);
                    self.line(format_args!("ret i64 {v}"));
                }
                Statement::ReturnBool(e) => {
                    let v = self.boolean(e);
                    self.line(format_args!("ret i1 {v}"));
                }
                Statement::DiscardInt(e) => {
                    self.int(e);
                }
                Statement::DiscardBool(e) => {
                    self.boolean(e);
                }
                Statement::CallVoid(c) => {
                    let args = self.arguments(c);
                    self.line(format_args!(
                        "call void @jai.p{}({args})",
                        c.procedure.index()
                    ));
                }
                Statement::Block(b) => self.block(b),
                Statement::If(c, yes, no) => {
                    let c = self.boolean(c);
                    let y = self.label();
                    let n = self.label();
                    let end = self.label();
                    self.line(format_args!("br i1 {c}, label %{y}, label %{n}"));
                    self.begin(y);
                    self.block(yes);
                    if yes.flow == Flow::FallsThrough {
                        self.jump(end);
                    }
                    self.begin(n);
                    self.block(no);
                    if no.flow == Flow::FallsThrough {
                        self.jump(end);
                    }
                    if yes.flow == Flow::FallsThrough || no.flow == Flow::FallsThrough {
                        self.begin(end);
                    }
                }
                Statement::While(c, body) => {
                    let test = self.label();
                    let inside = self.label();
                    let end = self.label();
                    self.jump(test);
                    self.begin(test);
                    let c = self.boolean(c);
                    self.line(format_args!("br i1 {c}, label %{inside}, label %{end}"));
                    self.begin(inside);
                    self.block(body);
                    if body.flow == Flow::FallsThrough {
                        self.jump(test);
                    }
                    self.begin(end);
                }
            }
        }
    }
    fn arguments(&mut self, call: &Call) -> String {
        let mut args = String::new();
        for (i, e) in call.arguments.iter().enumerate() {
            if i != 0 {
                args.push_str(", ");
            }
            match e {
                ValueExpr::Int(e) => {
                    let v = self.int(e);
                    write!(args, "i64 {v}").unwrap();
                }
                ValueExpr::Bool(e) => {
                    let v = self.boolean(e);
                    write!(args, "i1 {v}").unwrap();
                }
            }
        }
        args
    }
    fn int(&mut self, e: &IntExpr) -> IntOperand {
        match e {
            IntExpr::Constant(n) => IntOperand::Constant(*n),
            IntExpr::FromBool(e) => {
                let v = self.boolean(e);
                self.int_result(format_args!("zext i1 {v} to i64"))
            }
            IntExpr::Local(id) => {
                self.int_result(format_args!("load i64, ptr %local{}", id.index()))
            }
            IntExpr::Call(c) => {
                let args = self.arguments(c);
                self.int_result(format_args!(
                    "call i64 @jai.p{}({args})",
                    c.procedure.index()
                ))
            }
            IntExpr::Negate(e) => {
                let v = self.int(e);
                self.int_result(format_args!("sub i64 0, {v}"))
            }
            IntExpr::Complement(e) => {
                let v = self.int(e);
                self.int_result(format_args!("xor i64 {v}, -1"))
            }
            IntExpr::Binary(op, lhs, rhs) => {
                let lhs = self.int(lhs);
                let rhs = self.int(rhs);
                let op = match op {
                    IntOp::Add => "add",
                    IntOp::Subtract => "sub",
                    IntOp::Multiply => "mul",
                    IntOp::Divide => "sdiv",
                    IntOp::Remainder => "srem",
                    IntOp::BitAnd => "and",
                    IntOp::BitOr => "or",
                    IntOp::BitXor => "xor",
                    IntOp::ShiftLeft => "shl",
                    IntOp::ShiftRight => "ashr",
                };
                self.int_result(format_args!("{op} i64 {lhs}, {rhs}"))
            }
        }
    }
    fn boolean(&mut self, e: &BoolExpr) -> BoolOperand {
        match e {
            BoolExpr::Constant(b) => BoolOperand::Constant(*b),
            BoolExpr::FromInt(e) => {
                let v = self.int(e);
                self.bool_result(format_args!("icmp ne i64 {v}, 0"))
            }
            BoolExpr::Local(id) => {
                self.bool_result(format_args!("load i1, ptr %local{}", id.index()))
            }
            BoolExpr::Call(c) => {
                let args = self.arguments(c);
                self.bool_result(format_args!(
                    "call i1 @jai.p{}({args})",
                    c.procedure.index()
                ))
            }
            BoolExpr::Not(e) => {
                let v = self.boolean(e);
                self.bool_result(format_args!("xor i1 {v}, 1"))
            }
            BoolExpr::CompareInts(op, lhs, rhs) => {
                let lhs = self.int(lhs);
                let rhs = self.int(rhs);
                let op = match op {
                    Relation::Equal => "eq",
                    Relation::NotEqual => "ne",
                    Relation::Less => "slt",
                    Relation::LessEqual => "sle",
                    Relation::Greater => "sgt",
                    Relation::GreaterEqual => "sge",
                };
                self.bool_result(format_args!("icmp {op} i64 {lhs}, {rhs}"))
            }
            BoolExpr::CompareBools(op, lhs, rhs) => {
                let lhs = self.boolean(lhs);
                let rhs = self.boolean(rhs);
                let op = match op {
                    Equality::Equal => "eq",
                    Equality::NotEqual => "ne",
                };
                self.bool_result(format_args!("icmp {op} i1 {lhs}, {rhs}"))
            }
            BoolExpr::And(lhs, rhs) => self.short_circuit(lhs, rhs, Logical::And),
            BoolExpr::Or(lhs, rhs) => self.short_circuit(lhs, rhs, Logical::Or),
        }
    }
    fn short_circuit(&mut self, lhs: &BoolExpr, rhs: &BoolExpr, op: Logical) -> BoolOperand {
        let lhs = self.boolean(lhs);
        let left_block = self.current;
        let right_block = self.label();
        let join = self.label();
        let (yes, no, bypass) = match op {
            Logical::And => (right_block, join, false),
            Logical::Or => (join, right_block, true),
        };
        self.line(format_args!("br i1 {lhs}, label %{yes}, label %{no}"));
        self.begin(right_block);
        let rhs = self.boolean(rhs);
        let right_end = self.current;
        self.jump(join);
        self.begin(join);
        self.bool_result(format_args!(
            "phi i1 [ {}, %{left_block} ], [ {rhs}, %{right_end} ]",
            u8::from(bypass)
        ))
    }
}
enum Logical {
    And,
    Or,
}
