[package]
name = "jai-language-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "jai-lsp"
path = "src/main.rs"

[dependencies]
jai-source.workspace = true
jai-lexer.workspace = true
jai-syntax.workspace = true
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"

[lints]
workspace = true
