[package]
name = "jai-language-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "jailsp"
path = "src/main.rs"

[dependencies]
jaic = { path = "../jaic" }
jailint = { path = "../jailint" }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"

[lints]
workspace = true
