[package]
name = "jai-modules"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
[dependencies]
jai-source.workspace = true
jai-native-source.workspace = true
jai-syntax.workspace = true
jai-lexer.workspace = true
jai-eval.workspace = true
jai-types.workspace = true
[lints]
workspace = true
