//! Execute only programs generated by this Rust compiler from trusted fixtures.
#[path = "support/native_tools.rs"]
mod native_tools;
use std::{
    fs,
    process::Command,
    sync::atomic::{AtomicU64, Ordering},
    time::{Duration, Instant},
};

fn execute(source: &str, expected: i32) {
    execute_modes(source, expected, true);
}

fn execute_modes(source: &str, expected: i32, compare_vm: bool) {
    execute_sources(source, &[], expected, compare_vm);
}

enum Expectation {
    Exit(i32),
    Trap(jai_vm::Error),
}

fn execute_trap(source: &str, error: jai_vm::Error) {
    execute_sources_inner(source, &[], Expectation::Trap(error), true);
}

fn execute_sources(source: &str, files: &[(&str, &str)], expected: i32, compare_vm: bool) {
    execute_sources_inner(source, files, Expectation::Exit(expected), compare_vm);
}

fn execute_sources_inner(
    source: &str,
    files: &[(&str, &str)],
    expected: Expectation,
    compare_vm: bool,
) {
    static NEXT: AtomicU64 = AtomicU64::new(0);
    struct Scratch(std::path::PathBuf);
    impl Drop for Scratch {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }
    let scratch = Scratch(std::env::temp_dir().join(format!(
        "jai-sequences-{}-{}",
        std::process::id(),
        NEXT.fetch_add(1, Ordering::Relaxed)
    )));
    fs::create_dir(&scratch.0).unwrap();
    let input = scratch.0.join("main.jai");
    fs::write(&input, source).unwrap();
    for (name, source) in files {
        let path = scratch.0.join(name);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, source).unwrap();
    }
    let graph = jai_modules::ModuleGraph::load(
        &input,
        jai_modules::GraphOptions {
            import_dirs: vec![scratch.0.join("modules")],
        },
    )
    .unwrap();
    let target = jai_codegen::target::NativeTarget::new().unwrap();
    let program = jai_sema::resolve_graph_with_options(
        &graph,
        &jai_sema::ResolveOptions {
            layout: Some(target.layout_policy().unwrap()),
            ..Default::default()
        },
        &mut jai_vm::NoEffects,
    )
    .unwrap();
    if compare_vm {
        let mut limits = jai_vm::Limits::default();
        if matches!(
            &expected,
            Expectation::Trap(jai_vm::Error::Limit(
                jai_vm::LimitKind::SequenceTemporaryBytes
            ))
        ) {
            // Isolate the shared backing budget from the VM's independent work cap.
            limits.fuel = 4_000_000;
        }
        let execution = jai_vm::execute(&program, limits);
        match (&expected, execution.outcome) {
            (Expectation::Exit(expected), jai_vm::Outcome::Complete(values)) => {
                assert_eq!(values[0].integer().unwrap().value(), i128::from(*expected))
            }
            (Expectation::Trap(expected), jai_vm::Outcome::Failed(error)) => {
                assert_eq!(&error, expected)
            }
            (_, other) => panic!("unexpected VM outcome: {other:?}"),
        }
    }
    let context = jai_codegen::Context::create();
    let module = jai_codegen::lower_for_target(&context, &program, &target).unwrap();
    let object = scratch.0.join("program.o");
    target.write_object(&module, &object).unwrap();
    let executable = scratch.0.join("program");
    let result = native_tools::clang_command()
        .arg(&object)
        .arg("-o")
        .arg(&executable)
        .output()
        .unwrap();
    assert!(
        result.status.success(),
        "{}\n{}",
        String::from_utf8_lossy(&result.stderr),
        module.print_to_string()
    );
    let mut process = Command::new(&executable).spawn().unwrap();
    let deadline = Instant::now() + Duration::from_secs(5);
    loop {
        if let Some(status) = process.try_wait().unwrap() {
            match &expected {
                Expectation::Exit(expected) => assert_eq!(status.code(), Some(*expected)),
                Expectation::Trap(_) => {
                    assert!(!status.success());
                    #[cfg(unix)]
                    {
                        use std::os::unix::process::ExitStatusExt;
                        assert!(
                            status.signal().is_some(),
                            "native fixture returned instead of trapping: {status:?}"
                        );
                    }
                }
            }
            break;
        }
        if Instant::now() >= deadline {
            process.kill().unwrap();
            process.wait().unwrap();
            panic!("generated sequence fixture timed out");
        }
        std::thread::sleep(Duration::from_millis(5));
    }
}

#[test]
fn fixed_arrays_copy_and_preserve_order() {
    execute(
        "counter := 0; next :: () -> int { counter += 1; return counter; } main :: () -> int { a: [3]int = .[next(), next(), next()]; b := a; a[1] = 9; return b[0]*10 + b[1]*10 + b[2] + a[1]; }",
        42,
    );
}

#[test]
fn byte_strings_preserve_embedded_zero_and_non_utf8() {
    execute(
        "pass :: (s: string) -> string { return s; } main :: () -> int { s := pass(\"A\\0\\xFF\"); return s.count + cast(int) s[0] + cast(int) s[1] + cast(int) s[2] - 281; }",
        42,
    );
}

#[test]
fn array_view_aliases_original_storage() {
    execute(
        "change :: (values: []int) -> int { values[1] = 40; return values.count; } main :: () -> int { a: [2]int = .[1, 2]; count := change(a); return a[1] + count; }",
        42,
    );
}

#[test]
fn fixed_array_returns_and_nested_record_elements() {
    execute(
        "Point :: struct { x: int; y: int = 2; } points :: () -> [2]Point { return .[.{x=20}, .{x=20}]; } main :: () -> int { values := points(); values[0].x += values[0].y; return values[0].x + values[1].x; }",
        42,
    );
}

#[test]
fn empty_sequence_counts_and_dynamic_default() {
    execute(
        "main :: () -> int { a: [0]int; b: []int = a; c: [..]int; s: string; if a.data != null return 1; if b.data != null return 2; if c.data != null return 3; if s.data != null return 4; return 42 + a.count + b.count + c.count + c.allocated + s.count; }",
        42,
    );
}

#[test]
fn sequence_loops_capture_once_and_bind_indices() {
    execute(
        "counter := 0; values :: () -> [3]int { counter += 1; return .[5, 6, 7]; } main :: () -> int { sum := 0; for value,index: values() { sum += value + index; } return sum * 2 + counter - 1; }",
        42,
    );
}

#[test]
fn sequence_loop_pointer_binding_mutates_array_and_skips_empty() {
    execute(
        "main :: () -> int { a: [2]int = .[10, 10]; for *value: a { value.* += 11; } empty: [0]int; for value: empty { return 1; } return a[0] + a[1]; }",
        42,
    );
}

#[test]
fn sequence_reverse_loop_and_string_bytes() {
    execute(
        "main :: () -> int { a: [3]int = .[1, 2, 3]; result := 0; for <value: a { result = result*10 + value; } sum := 0; for byte: \"\\0\\xFF\" { sum += cast(int) byte; } return result - sum - 24; }",
        42,
    );
}

#[test]
fn dynamic_descriptor_fields_and_indexing_use_backing_storage() {
    execute(
        "main :: () -> int { a: [3]int = .[10, 20, 30]; values: [..]int = .{count=2,data=a.data,allocated=3}; values[0] = 20; sum := 0; for value: values { sum += value; } return sum + values.allocated - values.count + 1; }",
        42,
    );
}

#[test]
fn dynamic_array_reallocation_uses_real_libc_storage() {
    execute_modes(
        "malloc :: (size: u64) -> *void #foreign \"malloc\"; realloc :: (memory: *void, size: u64) -> *void #foreign \"realloc\"; free :: (memory: *void) #foreign \"free\"; main :: () -> int { values: [..]int; values.data = cast,no_check(*int) malloc(8); if values.data == null return 1; values.allocated = 1; values.count = 1; values[0] = 20; values.data = cast,no_check(*int) realloc(cast(*void) values.data, 16); if values.data == null return 2; values.allocated = 2; values.count = 2; values[1] = 22; result := values[0] + values[1]; free(cast(*void) values.data); return result; }",
        42,
        false,
    );
}

#[test]
fn dynamic_mutations_preserve_storage_and_reject_invalid_sizes_before_allocating() {
    execute_modes(
        r#"
        realloc :: (memory:*void, size:u64)->*void #foreign "realloc";
        free :: (memory:*void) #foreign "free";
        reserve :: (array:*[..]int, desired:int)->bool {
            maximum := 9223372036854775807 / size_of(int);
            if desired < 0 || desired > maximum return false;
            if array.count < 0 || array.count > array.allocated return false;
            if desired <= array.allocated return true;
            memory := realloc(cast(*void) array.data, cast(u64) desired * cast(u64) size_of(int));
            if memory == null return false;
            array.data = cast,no_check(*int) memory;
            array.allocated = desired;
            return true;
        }
        add :: (array:*[..]int, item:int)->bool {
            maximum := 9223372036854775807 / size_of(int);
            if array.count < 0 || array.count >= maximum return false;
            if array.count >= array.allocated {
                desired := array.count + 1;
                if array.count <= maximum/2 desired = array.count*2;
                if desired < 8 desired = 8;
                if !reserve(array, desired) return false;
            }
            array.data[array.count] = item;
            array.count += 1;
            return true;
        }
        resize :: (array:*[..]int, desired:int)->bool {
            old_count := array.count;
            if !reserve(array, desired) return false;
            array.count = desired;
            for i: old_count..desired-1 array.data[i] = 0;
            return true;
        }
        ordered_remove :: (array:*[..]int, index:int)->bool {
            if index < 0 || index >= array.count return false;
            for i: index..array.count-2 array.data[i] = array.data[i+1];
            array.count -= 1;
            return true;
        }
        reset :: (array:*[..]int) {
            free(cast(*void) array.data);
            array.data = null;
            array.count = 0;
            array.allocated = 0;
        }
        main :: ()->int {
            array:[..]int;
            if ordered_remove(*array, 0) return 1;
            if reserve(*array, -1) return 2;
            if reserve(*array, 9223372036854775807) return 3;
            if !add(*array, 20) || !add(*array, 99) || !add(*array, 22) return 4;
            if !ordered_remove(*array, 1) return 5;
            if ordered_remove(*array, -1) || ordered_remove(*array, array.count) return 6;
            original := array.data;
            if !reserve(*array, array.allocated) || original != array.data return 7;
            if !resize(*array, 4) || array[2] != 0 || array[3] != 0 return 8;
            if !resize(*array, 2) return 9;
            answer := array[0] + array[1];
            reset(*array);
            if array.count != 0 || array.allocated != 0 || array.data != null return 10;
            reset(*array);
            return answer;
        }
        "#,
        42,
        false,
    );
}

fn reject(source: &str, fragment: &str) {
    static NEXT: AtomicU64 = AtomicU64::new(0);
    let path = std::env::temp_dir().join(format!(
        "jai-sequence-reject-{}-{}.jai",
        std::process::id(),
        NEXT.fetch_add(1, Ordering::Relaxed)
    ));
    fs::write(&path, source).unwrap();
    let graph =
        jai_modules::ModuleGraph::load(&path, jai_modules::GraphOptions::default()).unwrap();
    let error = jai_sema::resolve_graph(&graph).unwrap_err();
    fs::remove_file(&path).unwrap();
    assert!(
        error.message.contains(fragment),
        "unexpected diagnostic: {error:?}"
    );
}

#[test]
fn fixed_array_length_mismatches_are_rejected() {
    reject(
        "main :: () -> int { values: [2]int = .[1]; return 0; }",
        "length",
    );
}

#[test]
fn constant_string_names_cannot_be_mutated_through_indexing() {
    reject(
        "value :: \"abc\"; main :: () -> int { value[0] = 4; return 0; }",
        "mutable storage",
    );
}

#[test]
fn runtime_string_descriptors_preserve_immutable_literal_backing() {
    execute_trap(
        "main :: () -> int { value := \"abc\"; value[0] = 4; return 0; }",
        jai_vm::Error::ReadOnlyStorage,
    );
}

#[test]
fn temporary_array_views_cannot_be_returned() {
    reject(
        "bad :: (x: int) -> []int { return .[x, 2]; } main :: () -> int { return 0; }",
        "temporary",
    );
    reject(
        "bad :: (x: int) -> *void { return cast(*void) int.[x,2].data; } main :: () -> int { return 0; }",
        "temporary",
    );
    reject(
        "bad :: (x: int, flag: bool) -> []int { return ifx flag then int.[x,2] else int.[x,3]; } main :: () -> int { return 0; }",
        "temporary",
    );
    reject(
        "View :: struct { data: []int; } bad :: (x: int) -> View { return .{data=.[x,2]}; } main :: () -> int { return 0; }",
        "temporary",
    );
}

#[test]
fn constant_array_views_survive_procedure_return_and_empty_data_is_null() {
    execute(
        "values :: () -> []int { return .[20, 22]; } empty :: () -> []int { return .[]; } main :: () -> int { a := values(); b := empty(); if b.data != null return 1; return a[0] + a[1] + b.count; }",
        42,
    );
}

#[test]
fn constant_packed_record_views_survive_return_and_reuse_static_backing() {
    execute(
        "Packed :: struct { tag: u8; x: int; } #no_padding values :: () -> []Packed { return .[.{tag=1,x=20}, .{tag=2,x=22}]; } main :: () -> int { a := values(); b := values(); if a.data != b.data return 1; return a[0].x + b[1].x; }",
        42,
    );
}

#[test]
fn nonzero_array_defaults_are_bounded_before_materialization() {
    reject(
        "Point :: struct { x: int = 7; } values: [1048576]Point; main :: () -> int { return 0; }",
        "constant cell budget",
    );
}

#[test]
fn dynamic_array_views_preserve_data_and_capture_descriptor_once() {
    execute(
        "sum :: (values: []int) -> int { return values[0] + values[1]; } main :: () -> int { storage: [2]int = .[20,22]; dynamic: [..]int = .{count=2,data=storage.data,allocated=2}; return sum(cast([]int) dynamic); }",
        42,
    );
}

#[test]
fn typed_literal_constants_and_global_initializers_preserve_identity() {
    execute(
        "TEXT :: \"A\\0\\xFF\"; ALIAS :: TEXT; text: string = ALIAS; VALUES :: int.[20,22]; values := VALUES; main :: () -> int { LOCAL :: int.[1,2]; return values[0] + values[1] + text.count - LOCAL.count - 1; }",
        42,
    );
}

#[test]
fn static_array_literals_cannot_be_assigned_through_constant_names() {
    reject(
        "VALUES :: int.[1,2]; main :: () -> int { VALUES[0] = 7; return 0; }",
        "mutable storage",
    );
}

#[test]
fn named_static_literal_data_addresses_are_stable_across_calls() {
    execute(
        "NUMBERS :: int.[20,22]; address :: () -> *int { return NUMBERS.data; } main :: () -> int { if NUMBERS.data != address() return 1; TEXT :: \"abc\"; if TEXT.data != TEXT.data return 2; return NUMBERS[0] + NUMBERS[1]; }",
        42,
    );
}

#[test]
fn string_descriptors_can_reference_mutable_byte_storage() {
    execute(
        "main :: () -> int { bytes: [3]u8 = .[40,2,255]; text: string = .{count=3,data=bytes.data}; text.count = 2; bytes[0] = 20; return cast(int) text[0] + cast(int) text[1] + 20; }",
        42,
    );
}

#[test]
fn string_module_parameters_keep_member_access_and_typed_defaults() {
    execute_sources(
        "Lib :: #import \"Lib\"(Label=\"AB\"); main :: () -> int { value: Lib.Holder; return Lib.length() + value.text.count + cast(int) Lib.first() - 27; }",
        &[(
            "modules/Lib.jai",
            "#module_parameters(Label: string = \"default\"); Holder :: struct { text: string = Label; } length :: () -> int { return Label.count; } first :: () -> u8 { return Label[0]; }",
        )],
        42,
        true,
    );
}

#[test]
fn mixed_variadic_spreads_capture_in_source_order_and_before_named_tails() {
    execute(
        "counter:int=0; next::()->int{counter+=1;return counter;} change::(data:*int)->int{data[0]=99;return 4;} collect::(values:..int,extra:int=0)->int{return values[0]*10+values[1]*10+values[2]+extra;} main::()->int{data:=int.[2,8]; answer:=collect(next(),..data,extra=change(data.data));if counter!=1 return 1;if data[0]!=99 return 2;return answer;}",
        42,
    );
}

#[test]
fn mixed_variadic_pack_views_remain_valid_until_the_caller_returns() {
    execute(
        "borrow::(values:..int)->[]int{return values;} main::()->int{data:=int.[22]; values:=borrow(20,..data);return values[0]+values[1];}",
        42,
    );
}

#[test]
fn mixed_empty_spread_and_named_descriptor_forwarding() {
    execute(
        "sum::(values:..int,extra:int=0)->int{result:=extra;for value:values result+=value;return result;} main::()->int{empty:=int.[];data:=int.[20,22];return sum(42,..empty)+sum(values=..data)-42;}",
        42,
    );
}

#[test]
fn variadic_frame_escape_through_a_local_alias_traps() {
    execute_trap(
        "borrow::(values:..int)->[]int{return values;} leak::()->[]int{data:=int.[22]; alias:=borrow(20,..data); return alias;} main::()->int{values:=leak();return values[0]+values[1];}",
        jai_vm::Error::SequenceTemporaryEscape,
    );
}

#[test]
fn repeated_variadic_concatenation_has_a_cumulative_frame_limit() {
    execute_trap(
        "count::(values:..int)->int{return values.count;} main::()->int{data:[1000]int;result:=0;for i:0..100 result+=count(i,..data);return result;}",
        jai_vm::Error::Limit(jai_vm::LimitKind::SequenceTemporaryBytes),
    );
}

#[test]
fn direct_variadic_forwarder_escape_has_a_source_diagnostic() {
    reject(
        "borrow::(values:..int)->[]int{return values;} leak::()->[]int{data:=int.[22];return borrow(20,..data);} main::()->int{return 0;}",
        "variadic pack storage",
    );
}

#[test]
fn mixed_any_spread_retains_existing_boxes() {
    execute(
        "sum::(values:..Any)->int{result:=0;for value:values result+=(cast(*int)value.value_pointer).*;return result;} main::()->int{boxed:Any=22;data: [1]Any=.[boxed];return sum(20,..data);}",
        42,
    );
}

#[test]
fn fixed_array_count_is_constant_without_running_an_initializer() {
    execute(
        "main::()->int{values:[42]int;#if values.count==42{return values.count;}else{return 1;}}",
        42,
    );
}

#[test]
fn dynamic_mutations_with_caller_backing_match_virtual_memory() {
    execute(
        "add::(array:*[..]int,item:int)->bool{if array.count<0 || array.count>=array.allocated return false;array.data[array.count]=item;array.count+=1;return true;} ordered_remove::(array:*[..]int,index:int)->bool{if index<0 || index>=array.count return false;for i:index..array.count-2 array.data[i]=array.data[i+1];array.count-=1;return true;} main::()->int{backing:[3]int;array:[..]int=.{count=0,data=backing.data,allocated=3};if ordered_remove(*array,0) return 1;if !add(*array,20)||!add(*array,99)||!add(*array,22) return 2;if add(*array,100) return 3;if ordered_remove(*array,-1)||ordered_remove(*array,array.count) return 4;if !ordered_remove(*array,1) return 5;return array[0]+array[1];}",
        42,
    );
}

#[test]
fn mixed_pack_rejects_oversized_and_null_nonempty_spreads_before_copying() {
    execute_trap(
        "count::(values:..int)->int{return values.count;} main::()->int{data:=int.[1];view:[]int=.{count=9223372036854775807,data=data.data};return count(1,..view);}",
        jai_vm::Error::Limit(jai_vm::LimitKind::SequenceTemporaryBytes),
    );
    execute_trap(
        "count::(values:..int)->int{return values.count;} main::()->int{view:[]int=.{count=1};return count(1,..view);}",
        jai_vm::Error::NullPointer,
    );
}

#[test]
fn nonempty_zero_size_variadic_elements_keep_a_nonnull_address() {
    execute(
        "Empty::struct{};inspect::(values:..Empty)->int{if values.data==null return 1;item:=values[1];return values.count+40;}main::()->int{data:[1]Empty;one:Empty;return inspect(one,..data);}",
        42,
    );
}

#[test]
fn generic_mixed_pack_infers_the_prefix_element_and_checks_the_spread() {
    execute(
        "sum::(values:..$T)->int{result:=0;for value:values result+=cast(int)value;return result;}main::()->int{data:=u16.[22];return sum(cast(u16)20,..data);}",
        42,
    );
}

#[test]
fn callback_mixed_pack_preserves_borrowed_return_lifetime() {
    execute(
        "borrow::(values:..int)->[]int{return values;}main::()->int{callback:=borrow;data:=int.[22];values:=callback(20,..data);return values[0]+values[1];}",
        42,
    );
}

#[test]
fn mutable_string_views_update_the_original_byte_storage() {
    execute(
        "mutate::(text:string){text[1]=0;text[0]+=1;}main::()->int{bytes:=u8.[19,99,22];text:string=.{count=3,data=bytes.data};alias:=text;mutate(alias);if bytes[1]!=0 || text[1]!=0 return 1;return cast(int)bytes[0]+cast(int)alias[2];}",
        42,
    );
}

#[test]
fn mutable_string_compound_indices_evaluate_once() {
    execute(
        "calls:int=0;next::()->int{calls+=1;return 0;}main::()->int{bytes:=u8.[40];text:string=.{count=1,data=bytes.data};text[next()]+=2;if calls!=1 return 1;return cast(int)text[0];}",
        42,
    );
}

#[test]
fn mutable_string_indexing_keeps_descriptor_bounds_checks() {
    execute_trap(
        "main::()->int{bytes:=u8.[42];text:string=.{count=1,data=bytes.data};text[1]=1;return 0;}",
        jai_vm::Error::OutOfBounds {
            index: 1,
            length: 1,
        },
    );
}

#[test]
fn formatter_unsigned_indices_do_not_require_a_signed_cast() {
    execute(
        "digit::(v:u64)->u8{base_64_characters::\"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_.\";base:u64=64;place:=v%base;return base_64_characters[place];}main::()->int{return cast(int)digit(42)-29;}",
        42,
    );
}

#[test]
fn unsigned_indices_preserve_aliases_and_evaluate_once() {
    execute(
        "calls:int=0;next::()->u64{calls+=1;return 1;}main::()->int{bytes:=u8.[20,99,22];text:string=.{count=3,data=bytes.data};text[next()]=0;view:[]u8=bytes;index:u32=2;if calls!=1 || view[cast(u8)1]!=0 return 1;return cast(int)view[cast(u16)0]+cast(int)text[index];}",
        42,
    );
}

#[test]
fn unsigned_indices_above_the_signed_range_fail_bounds_without_casting() {
    execute_trap(
        "main::()->int{bytes:=u8.[42];text:string=.{count=1,data=bytes.data};index:u64=18446744073709551615;return cast(int)text[index];}",
        jai_vm::Error::OutOfBounds {
            index: usize::MAX,
            length: 1,
        },
    );
}

#[test]
fn constant_unsigned_fixed_array_indices_receive_static_bounds_diagnostics() {
    reject(
        "main::()->int{values:[2]int;return values[cast(u64)18446744073709551615];}",
        "outside its fixed array bounds",
    );
}

#[test]
fn constant_captured_record_literals_keep_persistent_array_view_backing() {
    execute(
        "Pair::struct{value:int;}choose::()->[]Pair{return .[.{value=20},.{value=22}];}main::()->int{values:=choose();return values[0].value+values[1].value;}",
        42,
    );
}
