#!/usr/bin/env python3
"""Generate deny-only Rust receipts; inspect original native bytes without executing them."""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROOTS = ('reference', 'vendor', 'corpus/upstream')
MANIFESTS = ('corpus/reference-inputs.json', 'corpus/native-dependencies.json',
             'corpus/upstreams.json', 'corpus/original-native-inputs.json')
BINARIES = ('bin/jai-linux', 'bin/jai-macos', 'bin/jai.exe',
            'bin/lld-linux', 'bin/lld-macos', 'bin/lld.exe')
OUTPUT = 'crates/jai-driver/src/host_io/original_input_receipts.rs'
NATIVE_SUFFIXES = {'.a', '.lib', '.o', '.obj', '.so', '.dylib', '.dll', '.exe',
                   '.bc', '.wasm', '.spv', '.metallib', '.cubin', '.fatbin'}

def digest(path: Path) -> str:
    value = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            value.update(block)
    return value.hexdigest()

def native_file(path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    if path.suffix.lower() in NATIVE_SUFFIXES or '.so.' in path.name:
        return True
    with path.open('rb') as stream:
        magic = stream.read(8)
    return (magic.startswith((b'\x7fELF', b'MZ', b'!<arch>\n', b'\0asm', b'BC\xc0\xde')) or
            magic[:4] in (b'\xfe\xed\xfa\xce', b'\xce\xfa\xed\xfe',
                          b'\xfe\xed\xfa\xcf', b'\xcf\xfa\xed\xfe',
                          b'\xca\xfe\xba\xbe', b'\xbe\xba\xfe\xca',
                          b'\xca\xfe\xba\xbf', b'\xbf\xba\xfe\xca'))

def refresh_native(root: Path) -> dict:
    files = []
    missing = []
    for name in ROOTS:
        tree = root / name
        if not tree.exists():
            missing.append(name)
            continue
        if tree.is_symlink() or not tree.is_dir():
            raise ValueError(f'original inventory root is not a real directory: {name}')
        # Never follow symlink subtrees or inspect version-control internals.
        for directory, directories, names in os.walk(tree, followlinks=False):
            directory = Path(directory)
            directories[:] = sorted(d for d in directories if d != '.git' and
                                     not (directory / d).is_symlink())
            for leaf in sorted(names):
                path = directory / leaf
                if native_file(path):
                    files.append({'path': path.relative_to(root).as_posix(),
                                  'bytes': path.stat().st_size, 'sha256': digest(path)})
    return {'format': 1, 'provenance': 'Read-only native byte inventory; no execution, loading or linking.',
            'roots': list(ROOTS), 'missing_roots': missing, 'files': sorted(files, key=lambda f: f['path'])}

def checked_hash(value: str) -> str:
    if len(value) != 64 or any(c not in '0123456789abcdef' for c in value):
        raise ValueError('invalid canonical SHA256 receipt')
    return '[' + ', '.join('0x' + value[i:i + 2] for i in range(0, 64, 2)) + ']'

def generate(root: Path) -> str:
    manifests = {name: json.loads((root / name).read_text()) for name in MANIFESTS}
    if any(value.get('format') != 1 for value in manifests.values()):
        raise ValueError('unsupported inventory format')
    reference = {item['path']: item for item in manifests[MANIFESTS[0]]['files']}
    hashes = {reference[name]['sha256'] for name in BINARIES}
    native = manifests[MANIFESTS[-1]]
    if native['roots'] != list(ROOTS) or any(name not in ROOTS for name in native['missing_roots']):
        raise ValueError('native inventory differs from trusted root selectors')
    recorded = {item['path']: item for item in native['files']}
    if len(recorded) != len(native['files']):
        raise ValueError('duplicate original native artifact receipt')
    for name in BINARIES:
        item = recorded.get('reference/' + name)
        if item is not None and (item['sha256'] != reference[name]['sha256'] or
                                 item['bytes'] != reference[name]['bytes']):
            raise ValueError(f'original tool bytes differ from trusted reference receipt: {name}')
    for item in native['files']:
        path = Path(item['path'])
        if path.is_absolute() or '..' in path.parts or not any(path.is_relative_to(name) for name in ROOTS):
            raise ValueError('native receipt lies outside original roots')
        checked_hash(item['sha256'])
        hashes.add(item['sha256'])
    lines = ['// Generated by tools/generate_host_input_policy.py; deny authority only.',
             'pub(super) const ORIGINAL_ROOTS: &[&str] = &["reference", "vendor", "corpus/upstream"];',
             'pub(super) const MANIFEST_RECEIPTS: &[(&str, [u8; 32])] = &[']
    lines += [f'    ("{name}", {checked_hash(digest(root / name))}),' for name in MANIFESTS]
    lines += ['];', 'pub(super) const NATIVE_FINGERPRINTS: &[[u8; 32]] = &[']
    lines += ['    ' + checked_hash(value) + ',' for value in sorted(hashes)]
    lines += ['];', '']
    return '\n'.join(lines)

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--refresh-native', action='store_true',
                        help='Hash original native files read-only into the source-free byte inventory.')
    options = parser.parse_args()
    if options.check and options.refresh_native:
        parser.error('--check and --refresh-native are mutually exclusive')
    if options.refresh_native:
        (ROOT / MANIFESTS[-1]).write_text(json.dumps(refresh_native(ROOT), indent=2) + '\n')
    output = generate(ROOT)
    path = ROOT / OUTPUT
    if options.check:
        if path.read_text() != output:
            raise SystemExit('host original-input policy receipts are stale; regenerate after review')
        print('host original-input policy receipts match trusted manifests')
    else:
        path.write_text(output)

if __name__ == '__main__':
    main()
