[package]
name = "jai-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
divan.workspace = true
inkwell.workspace = true
jai-source.workspace = true
jai-lexer.workspace = true
jai-syntax.workspace = true
jai-eval.workspace = true
jai-sema.workspace = true
jai-codegen.workspace = true
jai-types.workspace = true
jai-ir.workspace = true
jai-vm.workspace = true
jai-modules.workspace = true

[[bench]]
name = "compiler"
harness = false

[[bench]]
name = "vm"
harness = false

[[bench]]
name = "discovery"
harness = false

[lints]
workspace = true
